route:
  receiver: slack
   
receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'x.x.x.x'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        send_resolved: true
        title: '{{ template "custom_title" . }}'
        text: '{{ template "custom_slack_message" . }}'
templates:
- /etc/alertmanager/notifications.tmpl